// Author: Ian D. Hanley | LinkedIn: /in/ianhanley/ | Twitter: @IanDHanley | Github: https://github.com/EEN421 | Blog: Hanley.cloud / DevSecOpsDad.com
// This is great for checking out your billable ingest patterns over the past quarter for QBRs etc. 
// If you see some wild highs and lows and need help making sense of the results, check out my KQL Detective series at hanley.cloud

//Query 1: This query will show you billable GB per day, by solution
Usage                                                                                   // <--Query the Usage table
| where TimeGenerated > ago(90d)                                                        // <--Query the last 90 days
| where IsBillable == true                                                              // <--Only include 'billable' data
| summarize TotalVolumeGB = sum(Quantity) / 1000 by bin(TimeGenerated, 1d), Solution    // <--Chop it up into GB / Day
| render columnchart                                                                    // <--Graph the results

//Query 2: This query is great for graphing out cost per day because CostUSD is float and not a string.
//You lose the '$' and '/day' formatting in the number column this way.
Usage                                                                                             // <--Query the Usage table
| where TimeGenerated > ago(90d)                                                                  // <--Query the last 90 days
| where IsBillable == true                                                                        // <--Only include 'billable' data
| summarize TotalVolumeGB = round(sum(Quantity) / 1024, 2) by StartTime=bin(TimeGenerated, 1d)    // <--Group data into 1-day buckets and convert total ingested quantity into GB
| extend CostUSD = round(TotalVolumeGB * 4.30, 2)                                   // <--Calculate daily cost by multiplying GB/day by your region’s $/GB rate and rounding to 2 decimals

//Query 3: The below query will return the total billable GB and incurred cost per day. 
//Because the cost is made into a string with strcat, it's not great for graphs. 
Usage                                                                                   // <--Query the Usage table
| where TimeGenerated > ago(90d)                                                        // <--Query the last 90 days
| where IsBillable == true                                                              // <--Only include 'billable' data
| summarize TotalVolumeGB = round(sum(Quantity) / 1024, 2) by bin(TimeGenerated, 1d)    // <--Chop it up into GB / Day
| extend  cost=strcat('$', round(TotalVolumeGB*4.30, 2), ' / Day')          // <--Format daily cost as a readable string by prepending '$', rounding to 2 decimals, and adding '/ Day'
| extend TotalVolumeGB = strcat(TotalVolumeGB, 'GB / Day')                  // <--Convert GB value to a display string by appending 'GB / Day' for clearer, human-friendly output

