Usage
|where TimeGenerated > ago(31d)
|where IsBillable == true
|summarize GB= sum(Quantity)/1000 by bin(TimeGenerated,1d)
|extend Cost=GB*DATAVALUE_PRICE_PER_GB
| summarize AvgCostPerDay=percentiles(Cost,50),AvgGBPerDay=percentiles(GB,50)
| project AvgGBPerDay=strcat(round(AvgGBPerDay,2), ' GB/Day (Past 31 Days)')
| extend Title = 'Avg Daily Consumption'

================================================================================

