// Author: Ian D. Hanley | LinkedIn: /in/ianhanley/ | Twitter: @IanDHanley | Github: https://github.com/EEN421 | Blog: Hanley.cloud / DevSecOpsDad.com
// This example queries the last 30 days of the syslog table, aggregates the number of hits per day, and the graphs results

Syslog                                          // <--Define the table to query
| where TimeGenerated > ago(30d)                // <--Query the last 30 days into the table
| summarize count() by bin(TimeGenerated,1d)    // <--Return count per day
| render columnchart                            // <--Graph a column chart
