// Ian D. Hanley | LinkedIn: /in/ianhanley/ | Twitter: @IanDHanley
// Ever wonder how many times each computer in your environment throws a specific EventID per day?

SecurityEvent                     // <--Define the table to query
| where EventID == "4663"         // <--Declare which EventID you're looking for
| summarize count() by Computer   // <--Show how many times that EventID was thrown per device
| render columnchart              // <--Optional, but helps quickly visualize potential outliers
